### PR TITLE
support lowering for aten.log1p

### PR DESCRIPTION
**Pull request by zezhang**
Lower aten.log1p op to  tcp.log(tcp.add(input, 1.0))

To test:

`bazel test //...` (in docker)

### CODE REVIEW

**Review by jain-sambhaav — COMMENTED** [review]
Can you add this to the aot_compile test suite for e2e coverage?

**Review by sjain-stanford — APPROVED** [review]
LGTM to land after this is added to aot_compile suite.

**Comment by zezhang** [comment]
> Can you add this to the aot_compile test suite for e2e coverage?

Just added.

**Comment by sjain-stanford** [comment]
There are two parity failures. 
```
[ RUN      ] AotCompiled.ExecuteTest
bazel-out/k8-fastbuild/bin/test/AotCompile/_internal_log1p_execute_test.cpp:139: Failure
Expected equality of these values:
  Result.Output0.data[i]
    Which is: -0.0529[184](https://github.com/cruise-automation/mlir-tcp/actions/runs/10687447249/job/29625079316#step:9:185)45
  refOutput0.data<float>()[i]
    Which is: -0.052918427

bazel-out/k8-fastbuild/bin/test/AotCompile/_internal_log1p_execute_test.cpp:139: Failure
Expected equality of these values:
  Result.Output0.data[i]
    Which is: -nan
  refOutput0.data<float>()[i]
    Which is: -nan
 ```

We use `EXPECT_FLOAT_EQ` which [checks](https://github.com/google/googletest/blob/main/docs/reference/assertions.md#expect_float_eq-expect_float_eq) two fp numbers are equal within 4 ULPs. Since this exceeds it, we might want to use a custom tolerance maybe with `EXPECT_NEAR`? Also not sure how this works for nans.

**Comment by zezhang** [comment]
> There are two parity failures.
> 
> ```
> [ RUN      ] AotCompiled.ExecuteTest
> 
> bazel-out/k8-fastbuild/bin/test/AotCompile/_internal_log1p_execute_test.cpp:139: Failure
> Expected equality of these values:
>   Result.Output0.data[i]
>     Which is: -0.0529[184](https://github.com/cruise-automation/mlir-tcp/actions/runs/10687447249/job/29625079316#step:9:185)45
>   refOutput0.data<float>()[i]
>     Which is: -0.052918427
> 
> bazel-out/k8-fastbuild/bin/test/AotCompile/_internal_log1p_execute_test.cpp:139: Failure
> Expected equality of these values:
>   Result.Output0.data[i]
>     Which is: -nan
>   refOutput0.data<float>()[i]
>     Which is: -nan
> ```
> 
> We use `EXPECT_FLOAT_EQ` which [checks](https://github.com/google/googletest/blob/main/docs/reference/assertions.md#expect_float_eq-expect_float_eq) two fp numbers are equal within 4 ULPs. Since this exceeds it, we might want to use a custom tolerance maybe with `EXPECT_NEAR`? Also not sure how this works for nans.

Right.... from PyTorch [Website](https://pytorch.org/docs/stable/generated/torch.log1p.html) Looks like `log1p` is better used with small input values.

**Comment by sjain-stanford** [comment]
Yeah you might want to try constraining the inputs to be positive and small (instead of torch.randn in the loader).

**Pull request merged**
